<a href="https://colab.research.google.com/github/sonky20/sonky/blob/master/1%EC%9D%BC%EC%B0%A8_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D%EC%8B%A4%EC%8A%B52.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import *
from sklearn.preprocessing import StandardScaler, MinMaxScaler

path = "https://bit.ly/graduate_csv"
data2 = pd.read_csv(path)
data2.head()

   admit  gre   gpa  rank
0      0  380  3.61     3
1      1  660  3.67     3
2      1  800  4.00     1
3      1  640  3.19     4
4      0  520  2.93     4

In [3]:
target = 'admit'
x = data2.drop(target, axis=1)
y = data2.loc[:, target]

In [4]:
cat_cols = ['rank']
x = pd.get_dummies(x, columns=cat_cols, drop_first=True)
x.head()

   gre   gpa  rank_2  rank_3  rank_4
0  380  3.61   False    True   False
1  660  3.67   False    True   False
2  800  4.00   False   False   False
3  640  3.19   False   False    True
4  520  2.93   False   False    True

In [9]:
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=0.3, random_state=20)
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_val = scaler.transform(x_val)

In [10]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train, y_train)
pred = model.predict(x_val)

In [11]:
print(confusion_matrix(y_val, pred))

[[74 10]
 [26 10]]

In [13]:
print(classification_report(y_val, pred))

              precision    recall  f1-score   support

           0       0.74      0.88      0.80        84
           1       0.50      0.28      0.36        36

    accuracy                           0.70       120
   macro avg       0.62      0.58      0.58       120
weighted avg       0.67      0.70      0.67       120